// One-time asset step: self-host the brand fonts so the site has zero external
// font dependency (faster first paint, privacy-friendly, offline-resilient).
// Re-run with: node scripts/fetch-fonts.mjs
// Downloads are intentionally sequential to stay polite to the font CDN.
/* eslint-disable no-await-in-loop */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const families = [
  { name: 'Outfit', css: 'Outfit:wght@400;500;600;700;800', weights: [400, 500, 600, 700, 800] },
  { name: 'Inter', css: 'Inter:wght@400;500;600;700', weights: [400, 500, 600, 700] },
  { name: 'JetBrains Mono', css: 'JetBrains+Mono:wght@400;500;600;700', weights: [400, 500, 600, 700] }
];
const keepSubsets = new Set(['latin', 'latin-ext']);

const fontsDir = resolve(import.meta.dirname, '../public/fonts');
await mkdir(fontsDir, { recursive: true });

const slug = (s) => s.toLowerCase().replace(/\s+/g, '-');
let out = '/* Self-hosted brand fonts — generated by scripts/fetch-fonts.mjs */\n';

for (const fam of families) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.text());

  // Split into @font-face blocks and map each to the `/* subset */` comment
  // that precedes it.
  const segments = css.split('@font-face');
  const blocks = segments.slice(1);
  const commentRe = /\/\*\s*([a-z-]+)\s*\*\//g;
  let currentSubset = 'latin';
  const subsetForIndex = [];
  for (let i = 1; i < segments.length; i++) {
    const matches = [...segments[i - 1].matchAll(commentRe)];
    if (matches.length) currentSubset = matches[matches.length - 1][1];
    subsetForIndex.push(currentSubset);
  }

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    const subset = subsetForIndex[i] ?? 'latin';
    if (!keepSubsets.has(subset)) continue;
    const weightMatch = block.match(/font-weight:\s*(\d+)/);
    const srcMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!weightMatch || !srcMatch) continue;
    const weight = weightMatch[1];
    const fileName = `${slug(fam.name)}-${weight}-${subset}.woff2`;
    const buf = Buffer.from(await fetch(srcMatch[1], { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()));
    await writeFile(resolve(fontsDir, fileName), buf);
    const rangeMatch = block.match(/unicode-range:\s*([^;]+);/);
    out +=
      `@font-face {\n` +
      `  font-family: '${fam.name}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${fileName}') format('woff2');\n` +
      (rangeMatch ? `  unicode-range: ${rangeMatch[1].trim()};\n` : '') +
      `}\n`;
    console.info(`  saved ${fileName} (${(buf.length / 1024).toFixed(1)}kb)`);
  }
}

await writeFile(resolve(import.meta.dirname, '../src/styles/fonts.css'), out);
console.info('fonts.css written');
