import { z } from 'zod';
import { identifierSchema, relativePathSchema } from './primitives.ts';

// Config family schema for `docstube.yml`.
//
// `docstube.yml` is the user-owned, comment-preserving config file. Per PRODUCT.md it carries
// intent only: doc type, site metadata, output, theme, personas, agent choices, source
// references, usage caps, and the IA/glossary file locations. It must never carry secrets,
// pipeline state, scores, findings, provenance, transcripts, or generated MDX.

// PascalCase registry component name (e.g. `Callout`, `Screenshot`).
export const componentNameSchema = z
  .string()
  .regex(/^[A-Z][A-Za-z0-9]*$/, { error: 'component name must be PascalCase' });

// Site metadata used by the generated docs site.
export const siteMetadataSchema = z.strictObject({
  name: z.string().min(1, { error: 'site name must not be empty' }),
  description: z.string().optional(),
  url: z.url({ error: 'site url must be a valid URL' }).optional(),
  locale: z.string().min(2).default('en')
});

export type SiteMetadata = z.infer<typeof siteMetadataSchema>;

// Doc-type intent. The setup wizard can infer one during project initialization.
export const docsTypes = ['library', 'application', 'api', 'cli', 'service'] as const;

export const docsTypeSchema = z.enum(docsTypes);

export type DocsType = z.infer<typeof docsTypeSchema>;

// Layouts are intentionally limited to `single-tree` and `sectioned` (PRODUCT.md decision log).
export const layouts = ['single-tree', 'sectioned'] as const;

export const layoutSchema = z.enum(layouts);

export type Layout = z.infer<typeof layoutSchema>;

export const outputSchema = z.strictObject({
  dir: relativePathSchema.default('docs'),
  layout: layoutSchema.default('single-tree')
});

export type OutputConfig = z.infer<typeof outputSchema>;

// Theme tokens are opaque string/number design values consumed by the generated theme.
export const themeSchema = z.strictObject({
  tokens: z.record(z.string(), z.union([z.string(), z.number()])).optional(),
  components: z.array(componentNameSchema).optional(),
  // "Generated by docstube" footer credit, default on and disableable (PRODUCT.md).
  credit: z.boolean().default(true)
});

export type ThemeConfig = z.infer<typeof themeSchema>;

export const personaSchema = z.strictObject({
  id: identifierSchema,
  title: z.string().min(1, { error: 'persona title must not be empty' }),
  description: z.string().optional(),
  goals: z.array(z.string().min(1)).optional()
});

export type Persona = z.infer<typeof personaSchema>;

// Built-in adapters: Codex (reference), Claude, Gemini, and a direct API adapter.
export const agentAdapters = ['codex', 'claude', 'gemini', 'api'] as const;

export const agentAdapterSchema = z.enum(agentAdapters);

export type AgentAdapterKind = z.infer<typeof agentAdapterSchema>;

// Provider presets for the direct API adapter. Custom OpenAI/Anthropic-compatible endpoints
// use `baseUrl` instead of, or alongside, a preset.
export const apiProviders = ['openai', 'anthropic'] as const;

export const apiProviderSchema = z.enum(apiProviders);

export type ApiProvider = z.infer<typeof apiProviderSchema>;

export const agentChoiceSchema = z
  .strictObject({
    adapter: agentAdapterSchema,
    model: z.string().min(1).optional(),
    provider: apiProviderSchema.optional(),
    baseUrl: z.url({ error: 'agent baseUrl must be a valid URL' }).optional()
  })
  .refine((choice) => choice.adapter !== 'api' || choice.provider !== undefined || choice.baseUrl !== undefined, {
    error: 'the api adapter requires a provider preset or a baseUrl',
    path: ['provider']
  });

export type AgentChoice = z.infer<typeof agentChoiceSchema>;

export const agentsSchema = z.strictObject({
  writer: agentChoiceSchema,
  reviewer: agentChoiceSchema.optional(),
  verifier: agentChoiceSchema.optional()
});

export type AgentsConfig = z.infer<typeof agentsSchema>;

// Source context references. Code wins every conflict; these are starting context only.
export const sourceReferenceSchema = z.discriminatedUnion('kind', [
  z.strictObject({ kind: z.literal('path'), path: relativePathSchema }),
  z.strictObject({
    kind: z.literal('git'),
    url: z.url({ error: 'git source url must be a valid URL' }),
    ref: z.string().min(1).optional()
  }),
  z.strictObject({ kind: z.literal('mcp'), server: z.string().min(1) })
]);

export type SourceReference = z.infer<typeof sourceReferenceSchema>;

// Usage caps are approximate by design. All limits are optional and must be positive.
export const usageCapsSchema = z.strictObject({
  maxUsd: z.number().positive().optional(),
  maxTokens: z.int().positive().optional(),
  maxPages: z.int().positive().optional()
});

export type UsageCaps = z.infer<typeof usageCapsSchema>;

// Reserved `screenshots:` config object.
//
// Screenshot capture is a hard TBD boundary in PRODUCT.md: reserve the config object and the
// `Screenshot` component name, but do not build capture flows. This schema accepts an object
// without triggering any screenshot implementation. It is intentionally loose so the reserved
// surface can grow without a breaking schema change.
export const screenshotsConfigSchema = z.looseObject({
  enabled: z.boolean().optional()
});

export type ScreenshotsConfig = z.infer<typeof screenshotsConfigSchema>;

export const docstubeConfigSchema = z.strictObject({
  version: z.literal(1).default(1),
  site: siteMetadataSchema,
  docsType: docsTypeSchema,
  output: outputSchema.default({ dir: 'docs', layout: 'single-tree' }),
  theme: themeSchema.optional(),
  personas: z.array(personaSchema).min(1, { error: 'at least one persona is required' }),
  agents: agentsSchema,
  sources: z.array(sourceReferenceSchema).optional(),
  caps: usageCapsSchema.optional(),
  // Committed IA and glossary file locations, relative to the config file.
  ia: relativePathSchema.default('ia.yml'),
  glossary: relativePathSchema.default('glossary.yaml'),
  screenshots: screenshotsConfigSchema.optional()
});

export type DocstubeConfig = z.infer<typeof docstubeConfigSchema>;
